# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/recommender.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/recommender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/recommender.proto\x12\x0brecommender\"$\n\x10RecommendRequest\x12\x10\n\x08item_ids\x18\x01 \x03(\x05\"%\n\x11RecommendResponse\x12\x10\n\x08item_ids\x18\x01 \x03(\x05\x32Y\n\x0bRecommender\x12J\n\tRecommend\x12\x1d.recommender.RecommendRequest\x1a\x1e.recommender.RecommendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.recommender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDREQUEST']._serialized_start=40
  _globals['_RECOMMENDREQUEST']._serialized_end=76
  _globals['_RECOMMENDRESPONSE']._serialized_start=78
  _globals['_RECOMMENDRESPONSE']._serialized_end=115
  _globals['_RECOMMENDER']._serialized_start=117
  _globals['_RECOMMENDER']._serialized_end=206
# @@protoc_insertion_point(module_scope)
